canonical/sdcore-nms-k8s-operator

.gitignore
CODEOWNERS
renovate.json
test-requirements.txt

Enables auto-merging of Renovate PRs if minor version of patch was changed.

Enable auto-merging Renovate PRs

---

.github/workflows/main.yaml
.gitignore
README.md
charmcraft.yaml
config.yaml
lib/charms/sdcore_upf/v0/fiveg_n4.py
metadata.yaml
requirements.txt
src/charm.py
tests/integration/test_integration.py
tests/unit/test_charm.py

Implements the requirer side of the `fiveg_n4` relation.
From now on, UPF hostname and port will be taken from the relation data instead of config params.
For now, the limit of connected `fiveg_n4` relations is set to one.
**Reference:**
https://docs.google.com/document/d/1s3U82GTUZFJ9mEhiHig0oAl44F0fq3eQT2PNv1uV75g

(Feat) Implementing fiveg_n4 requirer side

---

README.md
lib/charms/sdcore_gnbsim/v0/fiveg_gnb_identity.py
metadata.yaml
src/charm.py
tests/integration/test_integration.py
tests/unit/test_charm.py

Implements the requirer side of the `fiveg_gnb_identity` interface. The  `fiveg_gnb_identity`  relation is not mandatory.
At the moment we get the information from the relation databag but we do not do anything with it. 
Storage of relation data in config file is going to be done in a separate PR.
Check over the presence of `fiveg_n4` relation was removed since it's not mandatory either.
At the moment the `fiveg_n4` relation is limited to one. Implementation of multiple `fiveg_n4` relations  is going to be done in a separate PR.
Reference:
https://docs.google.com/document/d/1s3U82GTUZFJ9mEhiHig0oAl44F0fq3eQT2PNv1uV75g/edit

Implement requirer side of the fiveg_gnb_identity relation

---

src/charm.py

Removes unnecessary defers and observes `update_status` to re-evaluate charm state on a schedule.

feat: Removes unnecessary defers

---

tests/integration/test_integration.py

This is a fix for the integration test failure.
The reason was a 400 bad request due to an invalid header. The host used in the header contained a `/` at the end.
This is due to a change in the `show-proxied-endpoints` action from traefik. 
Before we used to get :  `"url": "http://test-traefik-sdcore-nms.pizza.com:80/"` 
And now we are getting:  `"url": "http://old-traefik-sdcore-nms.pizza.com/)"`
The observability team has not clarified if this change is expected.
The solution works in case we either get the port or not in the action result.

fix: integration tests failure

---

src/charm.py
tests/unit/expected_gnb.json
tests/unit/expected_upf.json
tests/unit/test_charm.py

Currently, if there are no Juju integrations between the nms operator and gnb/upf, the NMS would crash because there would be no gnb/upf config file. This PR here makes it so that a very basic config file containing nothing is created even if those relations do not exist. We also take advantage of this opportunity to get rid of all the patches made to filesystem operations in unit tests.

feat: Creates basic gnb/upf config files when no relation is created

---

tests/unit/test_charm.py

Removes unused unittest.mock.patch from imports in test_charm.py

fix: Removing unittest.mock.patch from imports in test_charm.py

---

.github/workflows/main.yaml
README.md
lib/charms/sdcore_gnbsim_k8s/v0/fiveg_gnb_identity.py
lib/charms/sdcore_upf_k8s/v0/fiveg_n4.py
lib/charms/sdcore_webui_k8s/v0/sdcore_management.py
metadata.yaml
src/charm.py
test-requirements.txt

Add -k8s as a suffix in both github and Charmhub name to follow [TE042](https://docs.google.com/document/d/1R0UzoPr3vvorhbBJYBz-5gZkTCTL2a9_R6xV8K4_i-8/edit).
- Add new fiveg_gnb_identity, fiveg_n4 and sdcore_management libraries
- Pin macaroonbakery to 1.3.2 which installed by juju client indirectly through pytest_operator.
- The next protobuf version 4.21.0 has the breaking changes with the existing code
- https://protobuf.dev/news/2022-05-06/#python-updates

chore: Rename SD-Core charms by adding -k8s as a suffix

---

requirements.txt

Pinning Pydantic<2.0 as Traefik-k8s ingress lib dependency to fix the integration tests

fix: Pinning Pydantic<2.0 as Traefik-k8s ingress lib dependency

---

src/charm.py
tests/unit/test_charm.py

This PR uses new ops feature CollectStatus Event to manage status Charm. Event named collect_unit_status sets the status of charm automatically at the end of every hook.

chore: Centralize status management

---

pyproject.toml
src/charm.py
test-requirements.in
test-requirements.txt
tests/integration/test_integration.py
tests/unit/test_charm.py
tox.ini

Move to ruff and codespell for linting. `pyproject-flake8` is currently broken on Python 3.12, making development on Noble break.

chore: Move to codespell and ruff 

---

src/charm.py
tests/unit/test_charm.py

fix https://github.com/canonical/sdcore-nms-k8s-operator/issues/90
Issue: Every time the update status event is fired, the Pebble service is restarted.
The Service name specified in Rockcraft is `nms`.
The one defined in the pebble layer is `sdcore-nms`. 
In every update status event, the container plan and the pebble layer were different, which triggered a service restart.

fix: NMS restart

---

src/charm.py
tests/unit/test_charm.py

fix https://github.com/canonical/sdcore-nms-k8s-operator/issues/27
Call the update gnb/upf config file methods on relation broken events.

fix: config file update on relation broken

---

metadata.yaml

This adds a simple change to the description to bump the OCI image with the fixed documentation links. This is required because the beta release currently has bad links to the documentation.

chore: Small change to use latest OCI image with fixed documentation links

---

tests/integration/test_integration.py

This is a workaround for https://github.com/canonical/traefik-k8s-operator/issues/361
A pydantic exception is raised when whe set to `subdomain` the routing_mode in traefik.
We need to add `nip.io` at the end of the external_hostname.
- Deploy traefik charm
- Wait for it to be idle
- Extract the traefik load balancer address using the `show-proxied-endpoints` action
- Configure the traefik charm 
```
"external_hostname": f"{traefik_ip}.nip.io",
"routing_mode": "subdomain"
```
- Obtain the NMS URL using the `show-proxied-endpoints` action. The URL looks like this:  `http://<model-name><nms-charm-name><traefik_ip>.nip.io/`
- Reach the NMS UI
There was a change in the Traefik charm:
The traefik-charm's public address is the load balancer external ip
The load balancer external ip is shown in …

fix: traefik integration test

---

tests/integration/test_integration.py

After issue https://github.com/canonical/traefik-k8s-operator/issues/361 
Traefik does not work with our integrations tests. 
As this is v1.4, we can freeze the traefik channel to `1.0/stable`

fix: freeze traefik channel 

---

tests/integration/test_integration.py

This PR add an integration test for the gNB/UPF inventory handling.
The NMS charm configures the gNB and UPF inventory on the webui, according to the relations joined.
The test:
- Add NMS charm, gnbsim charm, UPF charm and relate them.
- Check that the webui inventory contains the gNB and the UPF.
- Remove the gnbsim charm and the UPF charm.
- Check that the webui inventory no longer contains the gNB and the UPF.

feat: add integration test for gnb/upf webui inventory endpoints

---

CONTRIBUTING.md
src/charm.py
tests/unit/test_charm_workload_configuration.py

This PR set the webui URL in the sdcore_config relation to `{application_name}:5000`
Fixes https://github.com/canonical/sdcore-nms-k8s-operator/issues.

fix: nms grcp address

---

charmcraft.yaml

This PR aims to restore the storage size of `config` filesystem to 5M, after it was decreased to 1M. This modification is necessary to allow a seamless upgrade from Aether SD-Core 1.4 to 1.5, as Juju does not allow in-place upgrade of charms if there is a change in the storage definition

chore: restore storage size to 5M

---

src/charm.py
tests/unit/test_charm.py

A new Rock image from branch sdcore-nms 1.4 is created. This PR publishes the charm with this new image which has version 0.2.0.

chore: Dummy change to re-publish NMS charm with new Rock image

---

src/nms.py
tests/unit/test_nms.py

Here we centralize http calls into a `make_request` call. This allows for this client to scale as we will soon be adding a couple more methods to handle authentication. 
This is purely an implementation detail type issue where the user of this client is not impacted.
I'm going through a couple of quality changes in the context of adding authentication support
- #357 
- #357 
- #358 
I was going to initially bundle all of these together but I felt it was going to be easier to review if we separate quality improvements from features.

chore: centralize HTTP calls in nms client

---

src/nms.py

`config/v1/account/me` endpoint was used to validate token. This endpoint does not exist in the webui so we were getting lots of error logs. Also, the token secret was unnecessarily updated.
```
unit-sdcore-nms-k8s-0: 12:05:25 ERROR unit.sdcore-nms-k8s/0.juju-log Request failed: code 404
```

fix: use a valid endpoint to validate auth token

---

README.md
src/charm.py
src/nms.py
tests/integration/test_integration.py
tests/unit/test_charm_configure.py

Integration tests are unstable. It seem like we try to reach the list of gnbs before the gnbsim was added to the inventory due to a failed log in attempt.
This PR:
- Sets the mongodb channel to 6/stable
- Fixes the failed log in attempt. 
- A `CreateUserResponse` including an ID was expected from the POST user account endpoint, but the webui returns None after user successful creation. `CreateUserResponse` was removed.
- This fix removes the log errors about the first user creation and leads to immediate login after user creation.
- Restores integration tests related status blocked when DB is removed (https://github.com/canonical/mongodb-k8s-operator/issues/218 seems fixed in `6/stable`)
- Separate `_get_or_create_admin_account` into 2 functions to separate their responsibility.

fix: stabilize integration tests.

---

src/nms.py
tests/integration/test_integration.py

This PR adds an integration test.
After removing the DB application the webui DB is removed but the credentials secret is kept.
After mongoDB is removed and restored, we test that the secret credentials and DB credentials are aligned and we can log in using them.

chore: add token verification after restoring DB test

---

tests/integration/test_integration.py

Bumps version of AMF and gnbsim to `1.6/edge` in integration tests

chore: Bumps version of AMF and gnbsim to 1.6

---

.github/renovate.json5
.github/workflows/1_5_scheduled_runs.yaml

- Configures renovate to cover `v1.5`
- Adds `v1.5` scheduled CI runs

chore: Configures renovate to cover v1.5; adds v1.5 scheduled CI runs

---

.github/workflows/main.yaml

This PR fixes the wrong library names in workflows, causing CI failures.

fix: use correct library name

---

lib/charms/sdcore_nms_k8s/v0/sdcore_config.py

This PR bumps the patch version of `sdcore_config` library after #409.

chore: bump sdcore_config library patch version

---

src/nms.py
tests/unit/test_nms.py

Casts SD from hex to int
The SD value received in the Network Slice configuration is a hex, while the `fiveg_core_gnb` interface expects an int.

fix: Casts SD from hex to int

---

src/charm.py
src/nms.py
tests/unit/fixtures.py
tests/unit/test_charm_configure.py
tests/unit/test_nms.py

After https://github.com/omec-project/webconsole/pull/278 and https://github.com/omec-project/webconsole/pull/297 
We need to update the API calls in the charm.
We use POST to create and PUT to update gNBs and UPFs.
If a UPF/gNB updates it's port/tac in the relation, and the UPF/gNB already exists in the DB, we update it, instead of delete and recreate as before. This avoids sending unnecessary pebble notices 
NMS Image was updated here https://github.com/canonical/sdcore-nms/pull/720

feat: update API change in webconsole to edit UPFs and gNBs

---

charmcraft.yaml
src/charm.py
tests/unit/test_charm_configure.py
tox.ini

The URL of the swagger API documentation was not set properly when the application is behind Traefik. This updates the Pebble layer to configure it properly based on the content of the ingress relation.
Fixes https://github.com/canonical/sdcore-nms/issues/715

fix: Expose swagger API at the right URL

---

src/nms.py
tests/integration/test_integration.py

`test_given_nms_related_to_upf_and_upf_status_is_active_then_nms_inventory_contains_upf_information _` is failing. The reason: the list of UPF in the NMS in empty.
https://github.com/canonical/sdcore-nms-k8s-operator/actions/runs/13311071002/job/37225370333
The reason is an invalid token:
`nms:nms.py:150 /config/v1/inventory/upf request failed: code 401`
The NMS restarts, then we update the token in the secret but when we retrieve the secret to sync the gNBs and UPFs, the token is not up to date. It takes a couple of seconds before the `secret-changed` event is fired.
we are in a race condition, in which the secrets are not up to date when we want to update the NMS DB, so the test is unstable.
```
services:
nms:
command: /bin/webconsole --cfg /nms/config/nmscfg.conf
environment: …
```

fix: fix integration tests unstability

---

src/charm.py

Generating a password with punctuation leads to issues in some rare occurrences (see details in #448 ). Here we remove punctuation from the password generated. Passwords will now only be composed of lowercase ascii, uppercase ascii, and digits.
Fixes #448 
```python
punctuation = r"""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""
```

fix: dont generate password with ponctuation

---

src/charm.py
src/nms.py
tests/integration/test_integration.py
tests/unit/test_charm_configure.py
tests/unit/test_nms.py

This PR addresses the improvements requested in #455:
* remove unused `tac` parameter in gNB creation model and function
* improve invalid gNB error including the name and the relation ID

chore: improve gNB creation

---

.gitignore
lib/charms/sdcore_nms_k8s/v0/fiveg_core_gnb.py
tests/unit/lib/charms/sdcore_nms_k8s/v0/test_fiveg_core_gnb_requirer_interface.py
tests/unit/test_charm_configure.py

This PR adds the regular expression validation for the gNB name in the `fiveg_core_gnb`.

chore: add name validation for gNB

---

tests/integration/test_integration.py

This PR removes a workaround and specifies the base instead of series for charms that support 2 bases.

chore: use base instead of series for deployment in integration tests
